### PR TITLE
Fix static attribute setters

### PR DESCRIPTION
**Pull request by ExE-Boss**
Fixes <https://github.com/jsdom/webidl2js/issues/199>

### CODE REVIEW

**Comment by TimothyGu** [comment]
This looks good, but I'm wondering if we can fix https://github.com/jsdom/webidl2js/issues/186 at the same time. I'm not entirely sure what the shape of the API should look like though… maybe `Impl.implementation.set${camelCase(attr)}(globalObject, value)`?

**Comment by domenic** [comment]
Chromium does it via `[CallWith=]` nonstandard extended attributes, so that the impl class opts in to the unusual parameters.

**Comment by domenic** [comment]
Anyway, my vote would be for merging this without blocking on the additional scope of #186. WDYT, @TimothyGu?

**Comment by TimothyGu** [comment]
I was hoping to get something decided before a major version bump, but that ship has sailed so this is fine for me.

**Pull request merged**
