### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by TimothyGu**
- Variadic argument handling in "get effective override" imported straight from the spec
- Use Map instead of Object.create(null) for Context#dictionaries/interfaces, something I've wanted to do for quite some time
- Move Impl.init check to interface runtime, to simplify build process and eliminates circular dependencies. This does add a conditional to the generated files, but realistically the performance cost should be minimal.

### CODE REVIEW

**Comment by domenic** [comment]
I tend to prefer using Object.create(null) for string-keyed maps, as the syntax is more convenient. Why switch?

Very excited about the circular dependency elimination.

**Comment by TimothyGu** [comment]
I was under the impression that `Map`s are designed from the start to handle this sort of tasks, and indeed they perform better than `Object.create(null)` on current and future V8 versions. It's also somewhat easier to iterate on the values of a `Map` w/o universal `Object.values()` support in supported Node.js versions. These reasons are all inconsequential though, so I'd be happy to defer to your judgement.

**Comment by TimothyGu** [comment]
@domenic Would it be possible for me to have write permission to this repo? I am in the jsdom org but not in any teams, nor was I added to any repo as a collaborator. Being able to merge PRs would make development much quicker and easier.

**Comment by domenic** [comment]
@TimothyGu done!

**Pull request merged**
